format_version: 10
pipelines:
  expense-destroy:
    group: terraformgroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-terraform.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:NlOzyD4Fe4iIwO82xlKPJg==:VEWZuEsazEq/guHN9lq+Qg=="
      vault_token: "AES:p1FTwMafz3bW9N0/m6u9Fw==:zv7tKo79MHyo6h2o+ZPs8iGzgHGrBLZnu/R8z9mrnwA="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev,action: destroy}
          approval: { type: manual }
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec: { command: bash, arguments: [run.sh] }
      - PROD:
          fetch_materials: true
          environment_variables: { env: dev}
          approval: { type: manual }
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec: { command: bash, arguments: [run.sh] }