format_version: 10
pipelines:
  tools-create:
    group: terraformgroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/tools-automation.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:NlOzyD4Fe4iIwO82xlKPJg==:VEWZuEsazEq/guHN9lq+Qg=="
      vault_token: "AES:dad4E55Y7tyN+u+sS1JR9Q==:pjdghRdgYql2Rd6gmpJkuAVvHYCMckIp3HXlmJfx2GM="
    stages:
     - create:
          fetch_materials: true
          environment_variables: { env: dev}
          approval: { type: manual }
          jobs:
            terraform:
              timeout: 0
              tasks:
                - exec: { command: terraform, arguments: ["init"] }
                - exec: { command: terraform, arguments: ["apply","-auto-approve"] }