format_version: 10
pipelines:
  prometheus:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/vikramdevopsb79/tools-automation
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:NlOzyD4Fe4iIwO82xlKPJg==:VEWZuEsazEq/guHN9lq+Qg=="
      vault_token: "AES:p1FTwMafz3bW9N0/m6u9Fw==:zv7tKo79MHyo6h2o+ZPs8iGzgHGrBLZnu/R8z9mrnwA="
    environment_variables:
      tool_name: prometheus
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - setup-tool-service.sh