format_version: 10
pipelines:
  backend:
    group: App-Deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:NlOzyD4Fe4iIwO82xlKPJg==:VEWZuEsazEq/guHN9lq+Qg=="
      vault_token: "AES:dad4E55Y7tyN+u+sS1JR9Q==:pjdghRdgYql2Rd6gmpJkuAVvHYCMckIp3HXlmJfx2GM="
    environment_variables:
      component: backend
    template: ansible-app-deployment
