format_version: 10
pipelines:
  frontend:
    group: App-Deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
        environment_variables:
          component: frontend
          secure_variables:
            SSH_PASSWORD: "AES:GJpOsKchZolqf2Gylrqymw==:48C77QmHmE7ihFUNFmoXRw=="
    template: ansible-app-deployment