format_version: 10
pipelines:
  mysql:
    group: App-Deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
       SSH_PASSWORD: "AES:Cug4/rz4L7ZGSR8QpQo80Q==:I/llXGj7WQP/u/PgVrCL0w=="
    environment_variables:
       component: mysql
    template: ansible-app-deployment