format_version: 10
pipelines:
  mysql:
    group: App-Deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
       SSH_PASSWORD: "AES:NlOzyD4Fe4iIwO82xlKPJg==:VEWZuEsazEq/guHN9lq+Qg=="
       vault_token: "AES:p1FTwMafz3bW9N0/m6u9Fw==:zv7tKo79MHyo6h2o+ZPs8iGzgHGrBLZnu/R8z9mrnwA="
    environment_variables:
       component: mysql
    template: ansible-app-deployment