format_version: 10
pipelines:
  mysql:
    group: App-Deployment
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ee32f55:
        git: https://github.com/vikramdevopsb79/expense-ansible.git
        shallow_clone: true
        auto_update: true
        branch: main
        secure_variables:
          SSH_PASSWORD: "AES:GJpOsKchZolqf2Gylrqymw==:48C77QmHmE7ihFUNFmoXRw=="
          environment_variables:
            component: mysql
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                    - run.sh
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
      - STAGE:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                    - run.sh
                    command: bash
                    run_if: passed